### ISSUE TITLE
VS2022编译不通过

### ISSUE THREAD

**Issue by Adnini983** [Patoke/re-plants-vs-zombies#19] opened 2024-09-14 09:15 UTC
环境是VS2022+Git Shell 直接编译不通过 是需要修改什么地方吗？
我不是很懂编程 希望能通俗一点 谢谢 
![捕获](https://github.com/user-attachments/assets/68aa545e-d019-4194-bd5b-3ffd0b4feaa2)

**Comment by minerscale** [comment] 2024-09-14 09:18
The project downloads stuff from the internet. I expect since you're writing Chinese you're in China. Probably a great firewall of China issue. If you're not gonna get in trouble try a VPN

**Comment by Adnini983** [comment] 2024-09-14 09:30
> The project downloads stuff from the internet. I expect since you're writing Chinese you're in China. Probably a great firewall of China issue. If you're not gonna get in trouble try a VPN

谢谢 网络问题解决了 现在是另一个问题 vs报错说找不到标识符 双击其中一条报错信息时发现确实有个空的双括号 这里是不是要填什么东西啊？
![捕获](https://github.com/user-attachments/assets/0ab703e2-14e2-478d-8c3c-355c5373b4ef)

**Comment by minerscale** [comment] 2024-09-14 09:44
Duplicate of #14

**Closed as completed by minerscale** 2024-09-14 09:44 UTC
